version: '3'
services:
  runai-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ubuntu:latest
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - ./:/app
    working_dir: /app
    command:
      - python3 ./server.py
#      - bin/buildlinux.sh

#networks:
#  offline:
#    external: true