version: "3.7"
services:
  app:
    restart: always
    container_name: runai
    image: runaiserver:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DISABLE_TELEMETRY=true
      - HF_ENDPOINT=""
      - HF_HUB_OFFLINE=true
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: /bin/bash
    command: -c "/app/test.sh"
    # set entrypoint
    # entrypoint: /bin/bash -c "python3 --version" #"python --version" #"/usr/local/miniconda3/envs/runai/bin/python /app/server.py"

#networks:
#  offline:
#    external: true