version: "3.6"
services:
  app:
    restart: always
    container_name: runai
    image: runaiserver:latest
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DISABLE_TELEMETRY=true
      - HF_ENDPOINT=""
      - HF_HUB_OFFLINE=true
      - PATH=/usr/local/cuda-11.7/bin:$PATH
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "50006:50006"
    volumes:
      - ./:/app
      - ~/stablediffusion:/usr/share/stablediffusion
    working_dir: /app
    entrypoint: /bin/bash
    command: -c "python3 server.py"
    runtime: nvidia
